name: CI/CD MLOps
on:
  push:
    branches: [ main, feature/cicd ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Lancer les tests
        run: python -m pytest tests/ -v

      - name: Configurer AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login sur ECR
        run: |
          aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}

      - name: Build et Push image Docker
        run: |
          docker build -f cicd/Dockerfile -t ${{ secrets.ECR_REPO_URI }}:latest .
          docker push ${{ secrets.ECR_REPO_URI }}:latest

      - name: Déployer sur ECS
        run: |
          aws ecs update-service --cluster MLOPS_RETAIL_BANK_Cluster --service mlops-catboost-service --force-new-deployment
